name: winas_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.2.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2
  outline_material_icons: 0.1.0

  # flutter/plugins
  path_provider: 0.5.0+1
  shared_preferences: 0.5.1+2
  url_launcher: 5.0.2
  package_info: 0.4.0+2
  device_info: 0.4.0+1
  connectivity: 0.4.2
  video_player: 0.10.0+4

  # redux
  redux: 3.0.0
  flutter_redux: 0.5.3
  redux_persist: 0.8.2

  # image
  image_picker: 0.5.0+9
  image_cropper: 1.0.0
  photo_manager: 0.3.3

  # video
  chewie: 0.9.6

  # wechat
  fluwx: 0.6.1

  # handle file
  open_file: 2.0.1+1
  share_extend: 1.0.8

  # async utility
  async: 2.0.8
  synchronized: 2.1.0

  # create uuid
  uuid: 2.0.0-rc1

  # calc sha256
  crypto: 2.0.6

  # wifi ssid
  wifi: 0.1.5

  # request
  dio: 2.1.1
  # fix bug in PUT List<int> method
  # dio:
  #   git: https://github.com/juncaixinchi/dio.git


  # custom modified packages
  #
  # draggable_scrollbar: 0.0.4
  # to use draggable-scrollbar with sliver list
  draggable_scrollbar:
    git: https://github.com/juncaixinchi/flutter-draggable-scrollbar.git

  # flutter_blue: 0.5.0
  # fix BLE connection bug
  flutter_blue:
    git: https://github.com/juncaixinchi/flutter_blue.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family:  Winas
      fonts:
        - asset: lib/icons/fonts/Winas.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
